const $=id=>document.getElementById(id),won=n=>(Math.round(n)||0).toLocaleString('ko-KR')+'원';
const guardRates={알루미늄:3500,SUS201:4200,SUS304:5200};
const jabaraRates={일반형:{201:{1200:80000,1500:100000},304:{1200:120000,1500:140000}},고급형:{201:{1200:110000,1500:130000},304:{1200:150000,1500:170000}}};
let mode='guard',material='알루미늄',items=[];
$('quoteDate').value=new Date().toISOString().slice(0,10);
function rateHtml(){
  if(mode==='guard'){
    return `<div class="rate-list"><div><b>알루미늄</b><strong>3,500원</strong></div><div><b>SUS201</b><strong>4,200원</strong></div><div><b>SUS304</b><strong>5,200원</strong></div></div><p class="formula">가로 × 세로 ÷ 90,000 = 계산칸수 <b>올림</b></p><p class="muted">계산칸수 × 재질단가 × 수량</p>`;
  }
  return `<table class="rate-table"><thead><tr><th>형태</th><th>재질</th><th>높이</th><th>1m 단가</th></tr></thead><tbody>
  <tr><td>일반형</td><td>SUS201</td><td>1200</td><td>80,000원</td></tr>
  <tr><td>일반형</td><td>SUS201</td><td>1500</td><td>100,000원</td></tr>
  <tr><td>일반형</td><td>SUS304</td><td>1200</td><td>120,000원</td></tr>
  <tr><td>일반형</td><td>SUS304</td><td>1500</td><td>140,000원</td></tr>
  <tr><td>고급형</td><td>SUS201</td><td>1200</td><td>110,000원</td></tr>
  <tr><td>고급형</td><td>SUS201</td><td>1500</td><td>130,000원</td></tr>
  <tr><td>고급형</td><td>SUS304</td><td>1200</td><td>150,000원</td></tr>
  <tr><td>고급형</td><td>SUS304</td><td>1500</td><td>170,000원</td></tr>
  </tbody></table><p class="formula">높이별 1m 단가 × 제작길이 × 수량</p><p class="muted">최소 주문 3m · 100파이 우레탄바퀴 선택 시 1m당 5,000원 추가</p>`;
}
function switchMode(next){mode=next;document.querySelectorAll('.product-switch button').forEach(b=>b.classList.toggle('active',b.dataset.product===next));const guard=$('guardForm'),jabara=$('jabaraForm');guard.classList.toggle('hidden',next!=='guard');jabara.classList.toggle('hidden',next!=='jabara');guard.setAttribute('aria-hidden',String(next!=='guard'));jabara.setAttribute('aria-hidden',String(next!=='jabara'));$('calcTitle').textContent=next==='guard'?'방범창 제품 계산':'스텐 자바라 제품 계산';$('rateContent').innerHTML=rateHtml();updateLive()}
document.querySelectorAll('.product-switch button').forEach(b=>b.onclick=()=>switchMode(b.dataset.product));
document.querySelectorAll('#materialTabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#materialTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');material=b.dataset.material;updateLive()});
['width','height','guardQty','jType','jMaterial','jHeight','jLength','jQty','bigWheel'].forEach(id=>$(id).addEventListener('input',updateLive));document.querySelectorAll('[name=jOption]').forEach(x=>x.addEventListener('change',updateLive));
function guardCalc(){const w=+$('width').value,h=+$('height').value,q=Math.max(1,+$('guardQty').value||1);if(!w||!h)return null;const count=Math.ceil(w*h/90000),unit=guardRates[material];return{kind:'guard',name:`방범창 (${material})`,spec:`${w.toLocaleString()} × ${h.toLocaleString()}`,unitName:'EA',measure:`${count}칸`,q,unit,amount:count*unit*q,note:$('guardNote').value.trim(),copy:`${w}×${h} / ${count}칸`}}
function jabaraCalc(){const type=$('jType').value,mat=$('jMaterial').value,height=$('jHeight').value,length=Math.max(3,+$('jLength').value||0),q=Math.max(1,+$('jQty').value||1);if(!length)return null;let unit=jabaraRates[type][mat][height];const opts=[...document.querySelectorAll('[name=jOption]:checked')].map(x=>x.value);if($('bigWheel').checked){opts.push('100파이 우레탄바퀴');unit+=5000}return{kind:'jabara',name:`스텐 자바라 ${type} (SUS${mat})`,spec:`H${height} × L${length}m`,unitName:'m',measure:`${length}m`,q,unit,amount:unit*length*q,note:[opts.join(', '),$('jNote').value.trim()].filter(Boolean).join(' / '),copy:`H${height} / ${length}m`}}
function currentCalc(){return mode==='guard'?guardCalc():jabaraCalc()}
function updateLive(){const c=currentCalc();$('selectedProduct').textContent=c?c.name:(mode==='guard'?`방범창 ${material}`:'스텐 자바라');$('measureLabel').textContent=mode==='guard'?'계산칸수':'제작길이';$('measureValue').textContent=c?c.measure:(mode==='guard'?'0칸':'0m');$('unitPrice').textContent=c?won(c.unit):'0원';$('linePrice').textContent=c?won(c.amount):'0원';$('status').textContent=c?(mode==='guard'?`${c.spec} = ${c.measure} 적용`:`${c.spec}, ${won(c.unit)}/m 적용`):(mode==='guard'?'가로와 세로를 입력해 주세요.':'제작길이를 입력해 주세요.')}
$('addItem').onclick=()=>{const c=currentCalc();if(!c){alert('필수 값을 입력해 주세요.');return}items.push(c);render();if(mode==='guard'){$('width').value='';$('height').value='';$('guardQty').value=1;$('guardNote').value=''}updateLive()};
function totals(){const supply=items.reduce((a,x)=>a+x.amount,0),vat=Math.round(supply*.1);return{supply,vat,grand:supply+vat}}
function render(){const body=$('itemsBody');body.innerHTML=items.length?items.map((x,i)=>`<tr><td>${i+1}</td><td>${x.name}</td><td>${x.spec}</td><td>${x.unitName}</td><td>${x.measure}</td><td>${x.q}</td><td>${won(x.unit)}</td><td><b>${won(x.amount)}</b></td><td>${x.note||''}</td><td><button class="delete" onclick="removeItem(${i})">삭제</button></td></tr>`).join(''):'<tr class="empty"><td colspan="10">제품을 계산해 견적 목록에 추가해 주세요.</td></tr>';const t=totals();$('supplyTotal').textContent=won(t.supply);$('vatTotal').textContent=won(t.vat);$('grandTotal').textContent=won(t.grand)}
window.removeItem=i=>{items.splice(i,1);render()};
$('resetAll').onclick=()=>{if(confirm('모든 입력 내용과 견적 목록을 초기화할까요?')){items=[];document.querySelectorAll('.form-grid input').forEach(x=>x.value='');$('quoteDate').value=new Date().toISOString().slice(0,10);render()}};
function buildQuote(){const val=id=>$(id).value||'-';$('qDate').textContent=val('quoteDate');$('qCompany').textContent=val('company');$('qManager').textContent=val('manager');$('qPhone').textContent=val('phone');$('qEmail').textContent=val('email');$('qProject').textContent=val('project');$('qItems').innerHTML=items.map((x,i)=>`<tr><td>${i+1}</td><td>${x.name}</td><td>${x.spec}</td><td>${x.unitName}</td><td>${x.measure}</td><td>${x.q}</td><td>${won(x.unit)}</td><td>${won(x.amount)}</td><td>${x.note||''}</td></tr>`).join('');const t=totals();$('qSupply').textContent=won(t.supply);$('qVat').textContent=won(t.vat);$('qGrand').textContent=won(t.grand);$('qGrandTop').textContent=`총금액 ${won(t.grand)} (V.A.T. 포함)`}
$('makeQuote').onclick=()=>{if(!items.length)return alert('견적 목록에 제품을 추가해 주세요.');buildQuote();$('quoteSheet').classList.add('open');window.scrollTo(0,0)};$('closeQuote').onclick=()=>{$('quoteSheet').classList.remove('open');window.scrollTo(0,0)};$('printQuote').onclick=()=>{buildQuote();window.print()};
$('copyQuote').onclick=async()=>{const t=totals(),lines=['[강동자바라 견적서]',`업체명: ${$('company').value||'-'}`,...items.map((x,i)=>`${i+1}. ${x.name} ${x.copy} / ${x.q}${x.unitName} / ${won(x.amount)}`),`총금액: ${won(t.grand)}`];await navigator.clipboard.writeText(lines.join('\n'));alert('견적내용을 복사했습니다.')};
$('saveJpg').onclick=async()=>{buildQuote();if(typeof html2canvas!=='function')return alert('이미지 기능을 불러오지 못했습니다.');const b=$('saveJpg'),old=b.textContent;b.disabled=true;b.textContent='JPG 만드는 중...';let stage;try{if(document.fonts?.ready)await document.fonts.ready;stage=document.createElement('div');stage.style.cssText='position:fixed;left:-10000px;top:0;width:794px;background:#fff';const clone=document.querySelector('.paper').cloneNode(true);clone.style.cssText='width:794px;min-height:1123px;margin:0;padding:60px;box-shadow:none;background:#fff';stage.appendChild(clone);document.body.appendChild(stage);const canvas=await html2canvas(clone,{scale:2,backgroundColor:'#fff',useCORS:true,logging:false,windowWidth:794});const a=document.createElement('a'),company=($('company').value||'고객').replace(/[\\/:*?"<>|]/g,'_'),date=$('quoteDate').value;a.download=`강동자바라_견적서_${company}_${date}.jpg`;a.href=canvas.toDataURL('image/jpeg',.95);a.click()}catch(e){console.error(e);alert('JPG 저장 중 오류가 발생했습니다.')}finally{stage?.remove();b.disabled=false;b.textContent=old}};
switchMode('guard');render();
