const rates={"알루미늄":3500,"SUS201":4200,"SUS304":5200};let material="알루미늄",items=[];
const $=id=>document.getElementById(id),won=n=>(n||0).toLocaleString("ko-KR")+"원";
$("quoteDate").value=new Date().toISOString().slice(0,10);
document.querySelectorAll("#materialTabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#materialTabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");material=b.dataset.material;updateLive()});
["width","height","qty"].forEach(id=>$(id).addEventListener("input",updateLive));
function calc(){const w=+$('width').value,h=+$('height').value,q=Math.max(1,+$('qty').value||1);if(!w||!h)return null;const cells=Math.ceil(w*h/90000),unit=rates[material],amount=cells*unit*q;return{material,w,h,q,cells,unit,amount,note:$('itemNote').value.trim()}}
function updateLive(){const c=calc();$('selectedMaterial').textContent=material;$('unitCount').textContent=c?c.cells+'칸':'0칸';$('unitPrice').textContent=c?won(c.unit):'0원';$('linePrice').textContent=c?won(c.amount):'0원';$('status').textContent=c?`${c.w.toLocaleString()} × ${c.h.toLocaleString()} ÷ 90,000 = ${c.cells}칸 적용`:'가로와 세로를 입력해 주세요.'}
$('addItem').onclick=()=>{const c=calc();if(!c){alert('가로와 세로 사이즈를 입력해 주세요.');return}items.push(c);render();$('width').value='';$('height').value='';$('qty').value=1;$('itemNote').value='';updateLive()};
function totals(){const supply=items.reduce((a,x)=>a+x.amount,0),vat=Math.round(supply*.1);return{supply,vat,grand:supply+vat}}
function render(){const body=$('itemsBody');if(!items.length)body.innerHTML='<tr class="empty"><td colspan="9">제품을 계산해 견적 목록에 추가해 주세요.</td></tr>';else body.innerHTML=items.map((x,i)=>`<tr><td>${i+1}</td><td>${x.material}</td><td>${x.w.toLocaleString()} × ${x.h.toLocaleString()}</td><td>${x.cells}</td><td>${x.q}</td><td>${won(x.unit)}</td><td><b>${won(x.amount)}</b></td><td>${x.note||''}</td><td><button class="delete" onclick="removeItem(${i})">삭제</button></td></tr>`).join('');const t=totals();$('supplyTotal').textContent=won(t.supply);$('vatTotal').textContent=won(t.vat);$('grandTotal').textContent=won(t.grand)}
window.removeItem=i=>{items.splice(i,1);render()};$('resetAll').onclick=()=>{if(confirm('모든 입력 내용과 견적 목록을 초기화할까요?')){items=[];document.querySelectorAll('.form-grid input').forEach(x=>x.value='');$('quoteDate').value=new Date().toISOString().slice(0,10);render()}};
$('makeQuote').onclick=()=>{if(!items.length){alert('견적 목록에 제품을 추가해 주세요.');return}buildQuote();$('quoteSheet').classList.add('open');$('quoteSheet').setAttribute('aria-hidden','false');window.scrollTo(0,0)};
$('closeQuote').onclick=()=>{$('quoteSheet').classList.remove('open');$('quoteSheet').setAttribute('aria-hidden','true');window.scrollTo(0,0)};$('printQuote').onclick=async()=>{buildQuote();document.body.classList.add('printing');if(document.fonts&&document.fonts.ready){await document.fonts.ready}requestAnimationFrame(()=>requestAnimationFrame(()=>window.print()))};window.addEventListener('afterprint',()=>document.body.classList.remove('printing'));
function buildQuote(){const val=id=>$(id).value||'-';$('qDate').textContent=val('quoteDate');$('qCompany').textContent=val('company');$('qManager').textContent=val('manager');$('qPhone').textContent=val('phone');$('qEmail').textContent=val('email');$('qProject').textContent=val('project');$('qItems').innerHTML=items.map((x,i)=>`<tr><td>${i+1}</td><td>방범창 (${x.material})</td><td>${x.w.toLocaleString()} × ${x.h.toLocaleString()}</td><td>EA</td><td>${x.cells}</td><td>${x.q}</td><td>${won(x.unit)}</td><td>${won(x.amount)}</td><td>${x.note||''}</td></tr>`).join('');const t=totals();$('qSupply').textContent=won(t.supply);$('qVat').textContent=won(t.vat);$('qGrand').textContent=won(t.grand);$('qGrandTop').textContent=`총금액 ${won(t.grand)} (V.A.T. 포함)`}
$('copyQuote').onclick=async()=>{const t=totals(),lines=[`[강동자바라 견적서]`,`업체명: ${$('company').value||'-'}`,`담당자: ${$('manager').value||'-'}`,`연락처: ${$('phone').value||'-'}`,...items.map((x,i)=>`${i+1}. 방범창(${x.material}) ${x.w}×${x.h} / ${x.cells}칸 / ${x.q}개 / ${won(x.amount)}`),`공급가액: ${won(t.supply)}`,`부가세: ${won(t.vat)}`,`총금액: ${won(t.grand)}`];await navigator.clipboard.writeText(lines.join('\n'));alert('견적내용을 복사했습니다.')};
updateLive();render();
